### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by almostjulian** [datalust/seq-input-healthcheck#11]
It would be great if this supported common auth options (basic or token)...

**Comment by nblumhardt** [comment]
Thanks for the suggestion :+1:

**Comment by TroySchmidt** [comment]
If it was in line with the .NET Core Authentication modes that can be added to the Health Check endpoints that is good as well.

**Comment by mio-moto** [comment]
Is there an update to this? If possible, I'd like to configure what kind of request is sent by adding certain headers, too.

**Comment by nblumhardt** [comment]
Hi @DarkMio - thanks for the note.

No, no update as yet, but the scheme we've implemented in _Seq.App.HttpRequest_, `AuthenticationHeader` and `OtherHeaders` settings, seems like it would work well here and should be reasonably straightforward to port:

https://github.com/datalust/seq-app-httprequest/blob/dev/src/Seq.App.HttpRequest/HttpApp.cs#L60

We'll aim to loop back around to this ourselves, but if anyone's interested in taking a look and potentially sending a PR in the meantime, that would be welcome too.

**Comment by DarkMio** [comment]
Oh, that would actually fully solve my problem, I think. Thank you for that!

**Comment by mio-moto** [comment]
Hej, we've (the company I'm working for) looked at what's to be done and I will contribute that as improvement in the near future.

Our Health API broadcasts system metrics that we want to keep authenticated, otherwise we've recently adopted seq internally and are very happy with it.

**Comment by mio-moto** [comment]
@almostjulian See the PR, you can test this with the dev-release now (or wait for the full release).
I believe this fixes the issue now.

**Comment by nblumhardt** [comment]
Full release is now on NuGet 👍 (v2.0.0)

**Comment by almostjulian** [comment]
Thanks everyone!
