### ISSUE TITLE
App stopped working

### ISSUE THREAD

**Issue by SeriousM** [datalust/seq-input-healthcheck#12]
Hi! I have some instances of the "Health Check Input" app running but suddenly they just stopped creating events. There are also no diagnostic events from the app which would indicate any problem - it just stopped.

Could you please help me resolve the issue?

**Comment by SeriousM** [comment]
Restarting Seq Server apparently restarts the app activity.

**Comment by nblumhardt** [comment]
Thanks for the report, Bernhard 👍 

Are any diagnostic events shown if you click the little &downarrow; beside the app instance name?

**Comment by SeriousM** [comment]
No, none at all. No event is tagged with an AppInstanceId matching my health check apps. Maybe you could implement some basic loggings like start, stop, crash?

**Comment by nblumhardt** [comment]
Thanks for the follow-up. These should already be being logged, but they'll be in the diagnostic report accessible at the bottom of _Settings > Diagnostics_. Feel free to send any of it through to support@ if you need a hand interpreting it.

(Did the app appear with the red "stopped" pip when it failed, or was it running-but-silent?)

Thanks again!

**Comment by SeriousM** [comment]
Alright, this happend again, 14 days after last restart. I just downloaded the diagnostic logs but couldn't find any errors, maybe you can find it?
I've send you an email to support@. Thank you.

**Comment by nblumhardt** [comment]
@SeriousM thank you! Your email pointed us in the right direction; I think we've tracked it down and I'll post updates now to: https://github.com/datalust/seq-tickets/issues/867

**Comment by nblumhardt** [comment]
The fix for this will be included in the next Seq 5.1 patch. We're looking to bring it forward, to next week if possible. Thanks again!

**Comment by SeriousM** [comment]
I'm glad to hear that!
