### ISSUE TITLE
can`t not install. error "no type marked with `[SeqApp]` could be found"

### ISSUE THREAD

**Issue by lyling** [datalust/seq-input-healthcheck#13]
"Package Seq.Input.HealthCheck could not be interrogated for app configuration: no type marked with `[SeqApp]` could be found."

seq version : 5.1.3004

**Comment by nblumhardt** [comment]
Thank you for the report, Nicholas.

I can't spot any related issues or reports, and can't reproduce this with Seq 5.1.3004 on Windows or Docker, which suggests it's possibly machine- or configuration-specific.

Would you be able to share which OS you're running this on, and if Windows, which version of the .NET Framework is installed?

If possible, upgrading to Seq 5.1.3200 would rule out any known bugs in 3004 that I've overlooked. 

Thanks!

**Comment by tsimbalar** [comment]
I've been using `Seq.Input.HealthCheck` without issues in Seq v5.1.3200 on Docker without issues as well.

**Comment by nblumhardt** [comment]
Closing as stale, but please let me know if you need any further help 👍
