### ISSUE TITLE
System.Net.Http.HttpRequestException: No such host is known

### ISSUE THREAD

**Issue by kmakibhussain** [datalust/seq-input-healthcheck#21]
I am using heathcheck app, to send requests every 60seconds. 
All is working fine, but sometimes the app is giving me an error alert as "**System.Net.Sockets.SocketException (11001): No such host is known**". 
I have noticed that, whenever it is taking more than 10 seconds to complete the GET request, then such errors are occurring.
Below is the screenshot of the error. 

![image](https://user-images.githubusercontent.com/58728590/104425462-e6ce1980-55aa-11eb-963c-c8a00aa3daf8.png)

Now, my question is what are the reasons behind this error, and how can I solve this problem.

@nblumhardt @KodrAus @larenelg or anyone who has faced this problem, please share your valuable comments

**Comment by larenelg** [comment]
Hi @kmakibhussain 

`System.Net.Http.HttpClient` errors are always a bit curly!

Possible reasons I can think of are: 
- could there be a dynamic DNS? or some sort of periodic DNS issue? HttpClient caches DNS, so when the DNS changes it might throw this exception
- is there a proxy or firewall between Seq and the URL you're hitting? Proxies can introduce funny behaviour.

Let us know if this helps give you any clues!

Cheers,
Larene

**Comment by kmakibhussain** [comment]
Thank you very much for your response. Based on your observations, I'm presenting my views for your considerations:

**About DNS:**
a. The DNS we are using is fixed. So, can it be a HttpClient caching problem?
b. The error is occurring randomly, so I think, it's not a periodic DNS issue.

**About proxy or firewall:**
       Proxy server: Currently we have configured an Nginx reverse proxy for our application where the timeout is set to 65 seconds. But when the error occurred, we see that the time elapsed is around 11 seconds.
       Firewall: There are no firewall settings configured that will block the Seq's HTTP/HTTPS requests. Since we are sending the "Get" request every 60 seconds, so every day we have in total 1440 requests, of which this error may or may not occur.

**NB: Not only for this URL, but we are also experiencing the same problem when connecting this seq-health-check app to other URLs as well.**

Please provide any suggestions. Thanks in advance.

**Comment by larenelg** [comment]
Thanks @kmakibhussain for that detailed information, and thank you for your patience. We've been discussing the issue as a team.

Do you mind sending a support request to `support@datalust.co` with your diagnostic report attached? (_Seq > Settings > Download a full diagnostic report_)

This will help us narrow down the problem quickly, we hope!

**Comment by nblumhardt** [comment]
Closing this as stale; if you're still running into any issues with this please let us know. Thanks!
