### ISSUE TITLE
Option to enable UseDefaultCredentials

### ISSUE THREAD

**Issue by rbooth84** [datalust/seq-input-healthcheck#25]
Add option to enable UseDefaultCredentials on the HttpClient.

This would be useful for our internal applications that uses NTLM auth. Currently when hitting these applications we only get a 401.

**Comment by nblumhardt** [comment]
Thanks for the suggestion :+1:

**Comment by nblumhardt** [comment]
We think at this point in time we won't pursue this, but we'd be happy to help with a fork if anyone wants to create one for their own use.

Otherwise, exposing an unauthenticated `/health` endpoint from the target apps would be the way to go.

Thanks again for the suggestion!
