### ISSUE TITLE
Use of Seq Api Key?

### ISSUE THREAD

**Issue by danielcodingpilot** [datalust/seq-input-healthcheck#26]
Is there a way to include a Seq Api Key to the logging entries of the Health Check? We would like to secure our ingest endpoint and just adding the ApiKey to the attached properties in the plugin configuration is not working.

![image](https://github.com/datalust/seq-input-healthcheck/assets/77451861/1ad08a32-8e8e-4429-938d-a9a0ecbfe4f3)

Thanks for your support

**Comment by KodrAus** [comment]
Hi @danielcodingpilot :wave:

Thanks for reaching out! You can require API keys for HTTP ingestion without needing to specify a key for your apps that produce log events. Since those apps are run by Seq itself they don't use that public ingestion path.

**Comment by danielcodingpilot** [comment]
Hi @KodrAus,

Thanks for your quick response and clarifying this one 👍
