### ISSUE TITLE
Ignore Certificates

### ISSUE THREAD

**Issue by neilsilver** [datalust/seq-input-healthcheck#34]
An option to ignore out of date / invalid certs  certs option would be useful!

ServerCertificateCustomValidationCallback

Ill try to submit a PR to familiarise myself with the application sdk.

**Comment by KodrAus** [comment]
Hi @neilsilver 👋

We try to avoid adding options to apps to by-pass TLS validation. If the certificate presented by the system being healthchecked is expired or invalid that seems like a problem with that system you’d want to know about. If it’s an internal system using a self-signed certificate then trusting that certificate on the Seq server would be the best solution.

**Comment by neilsilver** [comment]
Understood.

Yes this is more of the 2nd case - self signed internal systems.

If we are monitoring many of these then coming up with a process of trusting these on the seq server might be a option.

**Comment by neilsilver** [comment]
Expired or Invalid is definitely something you want to log if the expectation is that the certificate is valid normally!  

However I can see in many use cases in our industry where devices are on the network that we want to Health Check a simple device to see that its responsive even if its using a self-signed cert.
 
Many of these devices have very simple basic web pages for administration but if its just us I guess we can create a simple app for our own internal use

**Comment by KodrAus** [comment]
Trusting those certificates on the Seq server would be the preferred solution I think.

We also try to keep these apps fairly hackable and permissively licensed so another option some people who are stuck take is to fork the apps, make whatever modifications they need for it to work, and publish it to an internal feed to use in Seq. That could be something to consider too.
