### ISSUE TITLE
Feature request: Allow POST with body

### ISSUE THREAD

**Issue by rj-au** [datalust/seq-input-healthcheck#39]
Currently only HTTP GET is allowed.
Allowing the option to send a HTTP POST with a body will allow querying GraphQL endpoints too.

**Comment by liammclennan** [comment]
Hi @richard-stafflink 

Why do you need POST for GraphQL?

**Comment by rj-au** [comment]
I didn't realise GQL could accept HTTP GET requests:
https://graphql.org/learn/serving-over-http/#get-request

The default is POST for graphql-yoga, but looks like it can handle HTTP GET too:
https://github.com/graphql/graphql-http/tree/main/implementations/graphql-yoga

```
5A70 MAY accept application/x-www-form-urlencoded formatted GET requests
9C48 MAY NOT allow executing mutations on GET requests
```

Thanks @liammclennan 
All good - closing

**Comment by liammclennan** [comment]
Nice. I didn't know that either. Glad it works. :)
