### ISSUE TITLE
Suggestion : enrich healthcheck event with JSON response

### ISSUE THREAD

**Issue by tsimbalar** [datalust/seq-input-healthcheck#7]
I believe it is (quite) common to have a dedicated URL for a health check, and that the returned response would contain some very basic information about how the healthcheck went.

I could imagine that it would return something like : 

```json
{
  "API": {
     "responseTimeMs": 300,
     "status": "OK"
  },
  "DB": {
    "responseTimeMs": 249,
    "resultCount": 2930,
    "status": "OK"
  }
}
```

When the response content-type is JSON, having that data included as enrichment to the event means we could then use dashboards and alerts to visualize or react to it.

I guess it would even be a (somewhat hacky) way to show Business-related data (KPIs etc) in the dashboard.

**Comment by nblumhardt** [comment]
Thanks @tsimbalar - this one's interesting and on the radar; the main issue surrounding this is how not to generate overlarge events. Giving it some thought 👍

**Comment by nblumhardt** [comment]
#8 should cover this; it's possible to just use `@Properties` to capture a whole document, but things could be more interesting using expressions like `API.status = 'OK' and DB.status = 'OK'`, or `@Properties[*].status = 'OK'` or even `[API.status, DB.status]` to pull out/test the interesting bits!

**Comment by tsimbalar** [comment]
Nice ! 👍
